spring.application.name=ProjectProyash
server.port=8086

# ===============================
# Supabase PostgreSQL
# ===============================
spring.datasource.url=jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres?pgbouncer=true
spring.datasource.username=postgres.ypktafonsquflzrmhxiq
spring.datasource.password=Gai@rik19@03
spring.datasource.driver-class-name=org.postgresql.Driver