spring.application.name=ProjectProyash
server.port=${PORT:8087}


spring.config.import=optional:file:.env[.properties]

# ===============================
# Supabase PostgreSQL
# ===============================
spring.datasource.url=${SUPABASE_DB_URL}
spring.datasource.username=${SUPABASE_DB_USERNAME}
spring.datasource.password=${SUPABASE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


razorpay.key.id=rzp_test_TWQFVA9cUC4sYO
razorpay.key.secret=${RZP_SECRET}

adminCode=${adminCode}